---
title: "Dynamique des pop - Notes de travail"
---

# Quelques données 

- Dynamique des populations : https://fr.wikipedia.org/wiki/Dynamique_des_populations#Esp%C3%A8ces_en_comp%C3%A9tition
- Lodka-Voltera : https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations 

# Equation de dynamique de pop
$$
\frac{\partial N_1}{\partial t} = N1 [R_{1,1}(1-N_1/K_1)+R_{1,2}(1-N_2/K_2)]
$$
$$

1 - \frac{\alpha_{1,1}( N_1 +\alpha_{1,2} N_2)}{(\alpha_{1,2}\alpha_{2,2}N2)}
$$
# Concept 

- Milieu
  + Espèces
    + Population
        - taille initiale ($N_0$)
        - taille(temps)  ($N_t$)
        - Capacité de charge ($K$)
        - Taux de reproduction ($R$)
          - Taux de naissance
          - Taux de mortalité
          - Taux de migration
          
- Interactions définies entre les espèces $\alpha_{i,j}$

# Les classes à défiinir

## Milieu (Renan)

- identifiant : charactere
- especes : liste d'objets de la classe `Espece`

## Espece (Camille)

- identifiant : charactere
- populations : liste d'objets de la classe `Population`

## Population (Marion)

- identifiant : charactere
- capacite : une valeur numérique indiquant la taille 
             maximum de la population.
- taux : une valeur numérique indiquant le taux de reproduction 
             maximum de la population.
- taille : un vecteur de numérique indiquant la taille
           de la population au cours du temps

## Competition (Margot)

Une matrice carrée de taille nombre de population, 
par défaut diagonale est à $1/K_{pop}$ les autres valeurs sont à 0.
les populations en colonne affectent les populations en ligne
si > 0 -> réduit la population ligne
si < 0 -> favorise la population ligne

# Analyse des résultats

## Graphique

- Graphique population en fonction du temps au niveau de :
   + du milieu
   + de l'espèce
   + de la population
   
- Graphique comparaison simulation

solution faire une méthode as_tibble pour les types

- Milieu
- Espece
- Population

avec les colonnes

- Id du milieu        : Environment
- Id de l'espèce      : Species
- Id de la population : Population
- Temps               : Time
- Valeur              : Count









